### ISSUE TITLE
flags enums

### ISSUE THREAD

**Issue by kruxmeier** [binsync/binsync#433]
### Description

BinSync doesn't seem to serialize any flag that an enum is a flags enum like `enum __bitmask XYZ_Flags`.
```toml
[XYZ_Flags]
name = "XYZ_Flags"
[XYZ_Flags.members]
...
```
